// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalLegisAmbiental.Infrastructure.MySQL;

#nullable disable

namespace PortalLegisAmbiental.Infrastructure.Migrations
{
    [DbContext(typeof(EfDbContext))]
    [Migration("20231115215459_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.Ato", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("CaminhoArquivo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("CreatedById")
                        .IsRequired()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("DataAto")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ementa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("JurisdicaoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PossuiConteudo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PossuiHtml")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("TipoAtoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("JurisdicaoId");

                    b.HasIndex("TipoAtoId");

                    b.ToTable("Atos");
                });

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.Grupo", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.GrupoPermissao", b =>
                {
                    b.Property<ulong>("GrupoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("PermissaoId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GrupoId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("GrupoPermissao");
                });

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.Jurisdicao", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Jurisdicoes");
                });

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.Permissao", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permissoes");
                });

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.TipoAto", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TiposAtos");
                });

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.Usuario", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.UsuarioGrupo", b =>
                {
                    b.Property<ulong>("GrupoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("UsuarioId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GrupoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioGrupo");
                });

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.Ato", b =>
                {
                    b.HasOne("PortalLegisAmbiental.Domain.Entities.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalLegisAmbiental.Domain.Entities.Jurisdicao", "Jurisdicao")
                        .WithMany()
                        .HasForeignKey("JurisdicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalLegisAmbiental.Domain.Entities.TipoAto", "TipoAto")
                        .WithMany()
                        .HasForeignKey("TipoAtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Jurisdicao");

                    b.Navigation("TipoAto");
                });

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.GrupoPermissao", b =>
                {
                    b.HasOne("PortalLegisAmbiental.Domain.Entities.Grupo", "Grupo")
                        .WithMany("GrupoPermissoes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalLegisAmbiental.Domain.Entities.Permissao", "Permissao")
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.UsuarioGrupo", b =>
                {
                    b.HasOne("PortalLegisAmbiental.Domain.Entities.Grupo", "Grupo")
                        .WithMany("UsuarioGrupos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalLegisAmbiental.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioGrupos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("GrupoPermissoes");

                    b.Navigation("UsuarioGrupos");
                });

            modelBuilder.Entity("PortalLegisAmbiental.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioGrupos");
                });
#pragma warning restore 612, 618
        }
    }
}
